# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Vatsal Kadakia
description: "Hi I'm Vatsal, and I'm a Data Scientist/Analyst.  My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "New Jersey, USA"
resume_url: ""
avatar_image: "https://github.com/vatsalkadakia/vatsalkadakia.github.io/blob/master/img/posts/WhatsApp%20Image%202024-04-19%20at%2016.42.03_9b190e80%20Cropped.jpg"

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/vatsal-kadakia-760a3b1ab/" 
github: "https://github.com/vatsalkadakia"  

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

